[package]
name = "repo_analyser"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
